Repository IT-Academy-Social-Projects-KRV/Synergy, pull requests merged in 2021-12, with the labels that each got.

#38 fix styles for EmptyProjectList component
  client/src/components/ProjectList/EmptyProjectList/AdvancedLogo/Logo/Logo.jsx
  client/src/components/ProjectList/EmptyProjectList/AdvancedLogo/Logo/Logo.module.scss
  client/src/components/ProjectList/EmptyProjectList/AdvancedLogo/Logo/styles.js
  client/src/components/ProjectList/EmptyProjectList/AdvancedLogo/Name/Name.jsx
  client/src/components/ProjectList/EmptyProjectList/AdvancedLogo/Name/Name.module.scss
  client/src/components/ProjectList/EmptyProjectList/AdvancedLogo/Name/styles.js
  client/src/components/ProjectList/EmptyProjectList/Description/CreateNewProject/CreateNewProject.jsx
  client/src/components/ProjectList/EmptyProjectList/Description/CreateNewProject/CreateNewProject.module.scss
  client/src/components/ProjectList/EmptyProjectList/Description/CreateNewProject/styles.js
  client/src/components/ProjectList/EmptyProjectList/Description/Header/Header.jsx
  client/src/components/ProjectList/EmptyProjectList/Description/Header/Header.module.scss
  client/src/components/ProjectList/EmptyProjectList/Description/Header/styles.js
  client/src/components/ProjectList/EmptyProjectList/EmptyProjectList.jsx
  client/src/components/ProjectList/EmptyProjectList/EmptyProjectList.module.scss
  client/src/components/ProjectList/EmptyProjectList/styles.js
Labels: bug

#74 Feature 2.28 create post request for item
  client/src/redux/index.js
  client/src/redux/requests/itemRequest.js
Labels: enhancement

#75 Add base two buttons
  client/src/shared/Buttons/Approve.jsx
  client/src/shared/Buttons/Reject.jsx
  client/src/shared/Buttons/index.js
Labels: enhancement, fix

#80 Feature login save user
  client/src/components/Header/Header.jsx
  client/src/components/ProtectedRoute.js
  client/src/components/SideBar/SideBar.jsx
  client/src/redux/requests/projectListRequest.js
  client/src/redux/requests/userRequest.js
  client/src/routes/routes.js
Labels: bug, enhancement, front-end

#85 Fix underscores
  api/src/seeders/20211129220551-StatusData.js
  api/src/seeders/20211129224737-UserData.js
  api/src/seeders/20211129230128-ProjectData.js
  api/src/seeders/20211130151213-ItemData.js
  api/src/utils/helpers/filter.js
Labels: back-end

#82 Created separate file for each model
  api/config/passport.js
  api/src/dal/commentRepository.js
  api/src/dal/itemRepository.js
  api/src/dal/projectRepository.js
  api/src/dal/userRepository.js
  api/src/models/commentModel.js
  api/src/models/itemModel.js
  api/src/models/models.js
  api/src/models/modelsAssociations.js
  api/src/models/projectModel.js
  api/src/models/roleModel.js
  api/src/models/statusCategoryModel.js
  api/src/models/statusModel.js
  api/src/models/tokenModel.js
  api/src/models/userModel.js
Labels: back-end

#84 Feature creating jest test
  client/package-lock.json
  client/package.json
  client/src/components/Alert/AlertWindow.js
  client/src/components/BillSettings/BillSettings.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Loader/Loader.js
  client/src/tests/Alert.test.js
  client/src/tests/BillSettings.test.js
  client/src/tests/Footer.test.js
  client/src/tests/Header.test.js
  client/src/tests/Loader.test.js
Labels: front-end

#91 added constants && fix some code
  client/src/components/SideBar/SideBar.jsx
  client/src/consts/statusCode.js
  client/src/consts/statusRole.js
  client/src/consts/userRoles.js
  client/src/pages/ProjectListPage/ProjectList.jsx
  client/src/redux/requests/userRequest.js
  client/src/routes/routes.js
Labels: front-end

#93 Feature 2.51-2.52. Create services and axios structure.
  client/src/hooks/useAxios.js
  client/src/hooks/useHttp.js
  client/src/redux/requests/itemRequest.js
  client/src/redux/requests/projectListRequest.js
  client/src/redux/requests/projectRequest.js
  client/src/redux/requests/userRequest.js
  client/src/redux/store.js
  client/src/services/item.service.js
  client/src/services/projects.service.js
  client/src/services/user.service.js
Labels: enhancement, front-end

#94 Feature 2.31 create component for own item page
  client/src/assets/images/ItemImages/Vector.png
  client/src/configs/routes.js
  client/src/consts/variables.scss
  client/src/pages/ProjectPage/Project/ItemPage/ItemPage.jsx
  client/src/pages/ProjectPage/Project/ItemPage/ItemPage.module.scss
  client/src/pages/ProjectPage/Project/ItemPage/index.js
  client/src/pages/ProjectPage/Project/ProjectAddItems/ProjectAddItems.jsx
  client/src/pages/ProjectPage/Project/ProjectAddItems/ProjectAddItems.module.scss
  client/src/pages/ProjectPage/Project/TableExistItems/TableExistItems.jsx
  client/src/routes/routes.js
Labels: front-end

#98 Changed footer and other pages for better flexibility
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.module.scss
  client/src/consts/variables.scss
  client/src/pages/AuthorizationPage/Authorization.module.scss
  client/src/pages/AuthorizationPage/components/Login/Login.jsx
  client/src/pages/AuthorizationPage/components/Registration/Registration.jsx
  client/src/pages/CreatingProjectPage/CreatingProject.module.scss
  client/src/pages/ProjectPage/Project/Project.jsx
  client/src/pages/ProjectPage/Project/SingleProject.module.scss
  client/src/routes/routes.js
  client/src/routes/routes.scss
Labels: front-end

#101 Fix routes
  client/src/components/App/App.js
  client/src/components/Footer/Footer.jsx
  client/src/components/ProtectedRoute.js
  client/src/components/SideBar/SideBar.jsx
  client/src/components/SideBar/SideBarItem/SideBarItem.jsx
  client/src/components/SideBar/sidebarItems.js
  client/src/configs/routes.js
  client/src/consts/Authorization.module.scss
  client/src/pages/AuthorizationPage/Authorization.jsx
  client/src/pages/AuthorizationPage/components/Login/Login.jsx
  client/src/pages/AuthorizationPage/components/Registration/Registration.jsx
  client/src/pages/AuthorizationPage/index.js
  client/src/pages/ProjectListPage/ProjectList.jsx
  client/src/pages/ProjectListPage/components/ProjectListItem/ProjectListItem.jsx
  client/src/pages/ProjectPage/Project/ItemPage/ItemPage.jsx
  client/src/pages/ProjectPage/Project/ProjectAddItems/ProjectAddItems.jsx
  client/src/pages/ProjectPage/Project/TableExistItems/TableExistItems.jsx
  client/src/pages/ProjectPage/index.js
  client/src/redux/actions/userAction.js
  client/src/redux/reducers/userReducer.js
  client/src/redux/requests/userRequest.js
  client/src/redux/selectors/selectors.js
  client/src/routes/AuthRoute.js
  client/src/routes/UnauthenticatedRoute.js
  client/src/routes/route.js
  client/src/routes/routes.js
  client/src/services/user.service.js
  client/src/shared/Autorization/AutorizationFooter.jsx
  client/src/shared/Autorization/AutorizationHeader.jsx
Labels: fix, front-end

#97 refactoring tableExistItems
  client/src/consts/tableExistItems.js
  client/src/pages/ProjectPage/Project/TableExistItems/EnhancedTableHead/EnhancedTableHead.jsx
  client/src/pages/ProjectPage/Project/TableExistItems/EnhancedTableToolbar/EnhancedTableToolbar.jsx
  client/src/pages/ProjectPage/Project/TableExistItems/TableExistItems.jsx
  client/src/pages/ProjectPage/Project/TableExistItems/TableExistItems.module.scss
Labels: front-end

#104 Created user registration
  api/package-lock.json
  api/package.json
  api/src/controllers/userController.js
  api/src/dal/userRepository.js
  api/src/routes/index.js
  api/src/routes/userRouter.js
  api/src/services/userService.js
Labels: back-end

#103 Create unit tests for itemService and projectService
  api/.eslintrc
  api/src/services/itemService.js
  api/src/services/projectService.js
  api/tests/unit/.gitkeep
  api/tests/unit/itemService.spec.js
  api/tests/unit/projectService.spec.js
Labels: back-end

#100 Added sort and filter
  client/package.json
  client/src/pages/CreatingProjectPage/CreatingProject.jsx
  client/src/pages/CreatingProjectPage/components/Calendar/Calendar.jsx
  client/src/pages/ProjectListPage/ProjectList.jsx
  client/src/pages/ProjectListPage/ProjectList.module.scss
  client/src/pages/ProjectListPage/ProjectListTransition.scss
  client/src/pages/ProjectListPage/components/DateSortInputs/DateFinishInput.js
  client/src/pages/ProjectListPage/components/DateSortInputs/DateStartInput.js
  client/src/pages/ProjectListPage/components/Pagination/Pagination.scss
  client/src/pages/ProjectListPage/components/Pagination/PaginationBar.js
  client/src/pages/ProjectListPage/components/ProjectListItem/ProjectListItem.jsx
  client/src/pages/ProjectListPage/components/RangeInput/InputRange.module.scss
  client/src/pages/ProjectListPage/components/RangeInput/RangeInput.js
  client/src/pages/ProjectListPage/components/SearchNameInput/SearchNameInput.js
  client/src/pages/ProjectListPage/components/SearchNameInput/SearchNameInput.module.scss
  client/src/pages/ProjectListPage/components/SelectInput/SelectInputSortBy.js
  client/src/pages/ProjectListPage/components/SelectInput/SelectInputSortDirection.js
  client/src/pages/ProjectListPage/components/SortComponent/SortComponent.js
  client/src/pages/ProjectListPage/components/SortComponent/SortComponent.module.scss
  client/src/redux/index.js
  client/src/redux/reducers/projectListReducer.js
  client/src/redux/requests/projectListRequest.js
  client/src/redux/requests/projectListSortRequest.js
  client/src/redux/requests/projectRequest.js
  client/src/services/projects.service.js
Labels: front-end

#106 created error handler
  api/app.js
Labels: back-end

#107 Wrap by Link, refactored onClick method, changed element to Button
  client/src/components/Header/Header.jsx
Labels: fix, front-end

#108 Feature 3.4 3.5 settings customer admin
  api/src/constans/constants.js
  api/src/controllers/settingsController.js
  api/src/dal/settingsRepository.js
  api/src/routes/index.js
  api/src/routes/settingsRouter.js
  api/src/services/settingsService.js
Labels: back-end

#112 Create settings page for admin
  api/src/controllers/settingsController.js
  api/src/dal/settingsRepository.js
  api/src/services/settingsService.js
  api/src/services/userService.js
  client/src/assets/images/SettingsPageImages/cancel.svg
  client/src/assets/images/SettingsPageImages/changes_was_saved.svg
  client/src/assets/images/SettingsPageImages/resset_password_image.svg
  client/src/assets/images/SettingsPageImages/username-icon.svg
  client/src/components/Settings/Settings.jsx
  client/src/components/Settings/index.js
  client/src/consts/variables.scss
  client/src/pages/ProjectListPage/ProjectList.jsx
  client/src/pages/ProjectListPage/components/SortComponent/SortComponent.js
  client/src/pages/SettingsPage/components/AdminSettingsPage/AdminSettings.jsx
  client/src/pages/SettingsPage/components/AdminSettingsPage/AdminSettings.module.scss
  client/src/pages/SettingsPage/components/AdminSettingsPage/index.js
  client/src/pages/SettingsPage/components/UserSettingsPage/UserSettings.jsx
  client/src/pages/SettingsPage/components/UserSettingsPage/index.js
  client/src/pages/SettingsPage/style.jsx
  client/src/redux/requests/projectRequest.js
  client/src/redux/requests/userRequest.js
  client/src/routes/route.js
  client/src/services/user.service.js
  client/src/shared/Buttons/Save.jsx
  client/src/shared/Buttons/index.js
Labels: enhancement, front-end

#111 Feature joi validation
  api/package-lock.json
  api/package.json
  api/src/middlewares/.gitkeep
  api/src/middlewares/validate.js
  api/src/routes/itemRouter.js
  api/src/routes/projectRouter.js
  api/src/routes/userRouter.js
  api/src/validations/.gitkeep
  api/src/validations/schemas/index.js
Labels: enhancement, back-end

#114 Create registration logic
  client/src/pages/AuthorizationPage/components/Registration/Registration.jsx
  client/src/redux/requests/userRequest.js
  client/src/services/user.service.js
Labels: enhancement, front-end
