Repository IT-Academy-Social-Projects-KRV/Synergy, pull requests merged in 2022-01, with the labels that each got.

#122 3.26/move logic to components
  client/src/components/SideBar/sidebarItems.js
  client/src/configs/routes.js
  client/src/pages/ProjectListPage/ProjectList.jsx
  client/src/pages/ProjectListPage/components/ProjectListItem/ProjectListItem.jsx
  client/src/pages/ProjectPage/Dashboard.jsx
  client/src/pages/ProjectPage/Project/ItemPage/ItemPage.jsx
  client/src/pages/ProjectPage/Project/Project.jsx
  client/src/pages/ProjectPage/Project/TableExistItems/TableExistItems.jsx
  client/src/pages/ProjectPage/Project/index.js
  client/src/redux/actions/itemAction.js
  client/src/redux/actions/projectAction.js
  client/src/redux/index.js
  client/src/redux/reducers/itemReducer.js
  client/src/redux/reducers/projectReducer.js
  client/src/redux/reducers/rootReducer.js
  client/src/redux/requests/itemRequest.js
  client/src/redux/requests/projectRequest.js
  client/src/redux/selectors/selectors.js
  client/src/routes/route.js
Labels: front-end

#125 Made media-query for Authorization
  client/src/assets/images/AuthorizationImages/registrationLogo.png
  client/src/consts/styles/Authorization.module.scss
  client/src/consts/validation.module.scss
  client/src/consts/variables.scss
  client/src/pages/AuthorizationPage/components/Login/Login.jsx
  client/src/pages/AuthorizationPage/components/Registration/Registration.jsx
  client/src/pages/AuthorizationPage/style.jsx
  client/src/shared/Autorization/AutorizationFooter.jsx
  client/src/shared/Autorization/AutorizationHeader.jsx
Labels: front-end

#123 User password encoding and decoding
  api/src/dal/userRepository.js
  api/src/services/userService.js
Labels: back-end

#126 Feature 4.9 import button into item page
  client/src/pages/ProjectPage/Project/ItemPage/ItemPage.jsx
  client/src/pages/ProjectPage/Project/ItemPage/ItemPage.module.scss
  client/src/pages/ProjectPage/Project/ItemPage/style.jsx
Labels: front-end

#131 Feature/bill settings
  api/src/controllers/billSettingsController.js
  api/src/services/billSettingsService.js
  client/src/components/BillSettings/BillSettings.jsx
  client/src/components/BillSettings/BillSettings.module.scss
  client/src/services/billSettings.service.js
  client/src/shared/Buttons/.gitkeep
  client/src/shared/Buttons/Primary.jsx
  client/src/shared/Buttons/index.js
Labels: enhancement, front-end, back-end
